/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const PlantEntry = IDL.Record({
  'id' : IDL.Nat,
  'germinationDate' : IDL.Opt(Time),
  'soilType' : IDL.Text,
  'name' : IDL.Text,
  'seedStartDate' : Time,
  'dailyLightHours' : IDL.Float64,
});

export const idlService = IDL.Service({
  'createPlanting' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Float64, IDL.Opt(Time)],
      [IDL.Nat],
      [],
    ),
  'deletePlantEntry' : IDL.Func([IDL.Nat], [], []),
  'getAllPlantsSortedByName' : IDL.Func([], [IDL.Vec(PlantEntry)], ['query']),
  'getPlantEntry' : IDL.Func([IDL.Nat], [PlantEntry], ['query']),
  'updatePlantEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, Time, IDL.Float64, IDL.Opt(Time)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const PlantEntry = IDL.Record({
    'id' : IDL.Nat,
    'germinationDate' : IDL.Opt(Time),
    'soilType' : IDL.Text,
    'name' : IDL.Text,
    'seedStartDate' : Time,
    'dailyLightHours' : IDL.Float64,
  });
  
  return IDL.Service({
    'createPlanting' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Float64, IDL.Opt(Time)],
        [IDL.Nat],
        [],
      ),
    'deletePlantEntry' : IDL.Func([IDL.Nat], [], []),
    'getAllPlantsSortedByName' : IDL.Func([], [IDL.Vec(PlantEntry)], ['query']),
    'getPlantEntry' : IDL.Func([IDL.Nat], [PlantEntry], ['query']),
    'updatePlantEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, Time, IDL.Float64, IDL.Opt(Time)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };